language: python
python:
  - "2.7"
cache: pip
install:
  - pip install Flask==0.12.2
  - pip install numpy
  - pip install Pillow==5.1.0
  - pip install SimpleITK==1.1.0
script:
  - cd framework
  - python -m unittest discover -p "*_test.py" -v
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
