language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install flask-cors==3.0.6
  - pip install Flask==0.12.3
  - pip install numpy
  - pip install Pillow==5.1.0
  - pip install SimpleITK==1.1.0
  - pip install requests==2.20.0
  - pip install python-magic==0.4.15
  - pip install h5py==2.8.0
  - pip install coverage
  - pip install coveralls
script:
  - cd framework
  - coverage run --source modelhublib,modelhubapi -m unittest discover -p "*_test.py" -v
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - info@modelhub.ai
    on_success: change # default: change
    on_failure: always # default: always
